# Site settings
title: "开源测试"
url: "//opentesting.github.io"
paginate: 5
author:
    name: Guanfa
   # github:
    #email:opentesting@hotmail.com
    #gitcafe:
    #twitter:
    #facebook:
    #googleplus:
    #weibo:
atom_path: /atom.xml
rss_path: /rss.xml

# Build settings
kramdown:
    input: GFM
permalink: /:categories/:year-:month/:title.html
gems: [jekyll-paginate]
exclude: [Gemfile, Gemfile.lock, qrsync, Rakefile]
assets_path: /assets
sass:
    sass_dir: assets/_sass
    style: :compressed

# comment
comments:
    duoshuo:
        name: opentesting                      
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26

# tinysou.com
search:
    tinysou:
        engineKey: 

# 网站统计
#analytics:
 #   baidu:
  #      siteid:                             # 百度统计 js 代码后的字符串

